/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "K8snatApiImpl.h"

namespace polycube {
namespace service {
namespace api {

using namespace polycube::service::model;

namespace K8snatApiImpl {
namespace {
std::unordered_map<std::string, std::shared_ptr<K8snat>> cubes;
std::mutex cubes_mutex;

std::shared_ptr<K8snat> get_cube(const std::string &name) {
  std::lock_guard<std::mutex> guard(cubes_mutex);
  auto iter = cubes.find(name);
  if (iter == cubes.end()) {
    throw std::runtime_error("Cube " + name + " does not exist");
  }

  return iter->second;
}

}

void create_k8snat_by_id(const std::string &name, const K8snatJsonObject &jsonObject) {
  {
    // check if name is valid before creating it
    std::lock_guard<std::mutex> guard(cubes_mutex);
    if (cubes.count(name) != 0) {
      throw std::runtime_error("There is already a cube with name " + name);
    }
  }
  auto ptr = std::make_shared<K8snat>(name, jsonObject);
  std::unordered_map<std::string, std::shared_ptr<K8snat>>::iterator iter;
  bool inserted;

  std::lock_guard<std::mutex> guard(cubes_mutex);
  std::tie(iter, inserted) = cubes.emplace(name, std::move(ptr));

  if (!inserted) {
    throw std::runtime_error("There is already a cube with name " + name);
  }
}

void replace_k8snat_by_id(const std::string &name, const K8snatJsonObject &bridge){
  throw std::runtime_error("Method not supported!");
}

void delete_k8snat_by_id(const std::string &name) {
  std::lock_guard<std::mutex> guard(cubes_mutex);
  if (cubes.count(name) == 0) {
    throw std::runtime_error("Cube " + name + " does not exist");
  }
  cubes.erase(name);
}

std::vector<K8snatJsonObject> read_k8snat_list_by_id() {
  std::vector<K8snatJsonObject> jsonObject_vect;
  for(auto &i : cubes) {
    auto m = get_cube(i.first);
    jsonObject_vect.push_back(m->toJsonObject());
  }
  return jsonObject_vect;
}

std::vector<nlohmann::fifo_map<std::string, std::string>> read_k8snat_list_by_id_get_list() {
  std::vector<nlohmann::fifo_map<std::string, std::string>> r;
  for (auto &x : cubes) {
    nlohmann::fifo_map<std::string, std::string> m;
    m["name"] = x.first;
    r.push_back(std::move(m));
  }
  return r;
}

/**
* @brief   Create natting-table by ID
*
* Create operation of resource: natting-table*
*
* @param[in] name ID of name
* @param[in] internalSrc ID of internal-src
* @param[in] internalDst ID of internal-dst
* @param[in] internalSport ID of internal-sport
* @param[in] internalDport ID of internal-dport
* @param[in] proto ID of proto
* @param[in] value natting-tablebody object
*
* Responses:
*
*/
void
create_k8snat_natting_table_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const NattingTableJsonObject &value) {
  auto k8snat = get_cube(name);

  return k8snat->addNattingTable(internalSrc, internalDst, internalSport, internalDport, proto, value);
}

/**
* @brief   Create natting-table by ID
*
* Create operation of resource: natting-table*
*
* @param[in] name ID of name
* @param[in] value natting-tablebody object
*
* Responses:
*
*/
void
create_k8snat_natting_table_list_by_id(const std::string &name, const std::vector<NattingTableJsonObject> &value) {
  auto k8snat = get_cube(name);
  k8snat->addNattingTableList(value);
}

/**
* @brief   Create ports by ID
*
* Create operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] portsName ID of ports_name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
create_k8snat_ports_by_id(const std::string &name, const std::string &portsName, const PortsJsonObject &value) {
  auto k8snat = get_cube(name);

  return k8snat->addPorts(portsName, value);
}

/**
* @brief   Create ports by ID
*
* Create operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
create_k8snat_ports_list_by_id(const std::string &name, const std::vector<PortsJsonObject> &value) {
  auto k8snat = get_cube(name);
  k8snat->addPortsList(value);
}

/**
* @brief   Create rule by ID
*
* Create operation of resource: rule*
*
* @param[in] name ID of name
* @param[in] value rulebody object
*
* Responses:
*
*/
void
create_k8snat_rule_by_id(const std::string &name, const RuleJsonObject &value) {
  auto k8snat = get_cube(name);

  return k8snat->addRule(value);
}

/**
* @brief   Create append by ID
*
* Create operation of resource: append*
*
* @param[in] name ID of name
* @param[in] value appendbody object
*
* Responses:
* RuleDnatAppendOutputJsonObject
*/
RuleDnatAppendOutputJsonObject
create_k8snat_rule_dnat_append_by_id(const std::string &name, const RuleDnatAppendInputJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();
  return dnat->append(value);

}

/**
* @brief   Create dnat by ID
*
* Create operation of resource: dnat*
*
* @param[in] name ID of name
* @param[in] value dnatbody object
*
* Responses:
*
*/
void
create_k8snat_rule_dnat_by_id(const std::string &name, const RuleDnatJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();

  return rule->addDnat(value);
}

/**
* @brief   Create entry by ID
*
* Create operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value entrybody object
*
* Responses:
*
*/
void
create_k8snat_rule_dnat_entry_by_id(const std::string &name, const uint32_t &id, const RuleDnatEntryJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();

  return dnat->addEntry(id, value);
}

/**
* @brief   Create entry by ID
*
* Create operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] value entrybody object
*
* Responses:
*
*/
void
create_k8snat_rule_dnat_entry_list_by_id(const std::string &name, const std::vector<RuleDnatEntryJsonObject> &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();
  dnat->addEntryList(value);
}

/**
* @brief   Create masquerade by ID
*
* Create operation of resource: masquerade*
*
* @param[in] name ID of name
* @param[in] value masqueradebody object
*
* Responses:
*
*/
void
create_k8snat_rule_masquerade_by_id(const std::string &name, const RuleMasqueradeJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();

  return rule->addMasquerade(value);
}

/**
* @brief   Create disable by ID
*
* Create operation of resource: disable*
*
* @param[in] name ID of name
*
* Responses:
* RuleMasqueradeDisableOutputJsonObject
*/
RuleMasqueradeDisableOutputJsonObject
create_k8snat_rule_masquerade_disable_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto masquerade = rule->getMasquerade();
  return masquerade->disable();

}

/**
* @brief   Create enable by ID
*
* Create operation of resource: enable*
*
* @param[in] name ID of name
*
* Responses:
* RuleMasqueradeEnableOutputJsonObject
*/
RuleMasqueradeEnableOutputJsonObject
create_k8snat_rule_masquerade_enable_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto masquerade = rule->getMasquerade();
  return masquerade->enable();

}

/**
* @brief   Create append by ID
*
* Create operation of resource: append*
*
* @param[in] name ID of name
* @param[in] value appendbody object
*
* Responses:
* RulePortForwardingAppendOutputJsonObject
*/
RulePortForwardingAppendOutputJsonObject
create_k8snat_rule_port_forwarding_append_by_id(const std::string &name, const RulePortForwardingAppendInputJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  return portForwarding->append(value);

}

/**
* @brief   Create port-forwarding by ID
*
* Create operation of resource: port-forwarding*
*
* @param[in] name ID of name
* @param[in] value port-forwardingbody object
*
* Responses:
*
*/
void
create_k8snat_rule_port_forwarding_by_id(const std::string &name, const RulePortForwardingJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();

  return rule->addPortForwarding(value);
}

/**
* @brief   Create entry by ID
*
* Create operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value entrybody object
*
* Responses:
*
*/
void
create_k8snat_rule_port_forwarding_entry_by_id(const std::string &name, const uint32_t &id, const RulePortForwardingEntryJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();

  return portForwarding->addEntry(id, value);
}

/**
* @brief   Create entry by ID
*
* Create operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] value entrybody object
*
* Responses:
*
*/
void
create_k8snat_rule_port_forwarding_entry_list_by_id(const std::string &name, const std::vector<RulePortForwardingEntryJsonObject> &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  portForwarding->addEntryList(value);
}

/**
* @brief   Create append by ID
*
* Create operation of resource: append*
*
* @param[in] name ID of name
* @param[in] value appendbody object
*
* Responses:
* RuleSnatAppendOutputJsonObject
*/
RuleSnatAppendOutputJsonObject
create_k8snat_rule_snat_append_by_id(const std::string &name, const RuleSnatAppendInputJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();
  return snat->append(value);

}

/**
* @brief   Create snat by ID
*
* Create operation of resource: snat*
*
* @param[in] name ID of name
* @param[in] value snatbody object
*
* Responses:
*
*/
void
create_k8snat_rule_snat_by_id(const std::string &name, const RuleSnatJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();

  return rule->addSnat(value);
}

/**
* @brief   Create entry by ID
*
* Create operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value entrybody object
*
* Responses:
*
*/
void
create_k8snat_rule_snat_entry_by_id(const std::string &name, const uint32_t &id, const RuleSnatEntryJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();

  return snat->addEntry(id, value);
}

/**
* @brief   Create entry by ID
*
* Create operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] value entrybody object
*
* Responses:
*
*/
void
create_k8snat_rule_snat_entry_list_by_id(const std::string &name, const std::vector<RuleSnatEntryJsonObject> &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();
  snat->addEntryList(value);
}

/**
* @brief   Delete natting-table by ID
*
* Delete operation of resource: natting-table*
*
* @param[in] name ID of name
* @param[in] internalSrc ID of internal-src
* @param[in] internalDst ID of internal-dst
* @param[in] internalSport ID of internal-sport
* @param[in] internalDport ID of internal-dport
* @param[in] proto ID of proto
*
* Responses:
*
*/
void
delete_k8snat_natting_table_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto) {
  auto k8snat = get_cube(name);

  return k8snat->delNattingTable(internalSrc, internalDst, internalSport, internalDport, proto);
}

/**
* @brief   Delete natting-table by ID
*
* Delete operation of resource: natting-table*
*
* @param[in] name ID of name
*
* Responses:
*
*/
void
delete_k8snat_natting_table_list_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  k8snat->delNattingTableList();
}

/**
* @brief   Delete ports by ID
*
* Delete operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] portsName ID of ports_name
*
* Responses:
*
*/
void
delete_k8snat_ports_by_id(const std::string &name, const std::string &portsName) {
  auto k8snat = get_cube(name);

  return k8snat->delPorts(portsName);
}

/**
* @brief   Delete ports by ID
*
* Delete operation of resource: ports*
*
* @param[in] name ID of name
*
* Responses:
*
*/
void
delete_k8snat_ports_list_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  k8snat->delPortsList();
}

/**
* @brief   Delete rule by ID
*
* Delete operation of resource: rule*
*
* @param[in] name ID of name
*
* Responses:
*
*/
void
delete_k8snat_rule_by_id(const std::string &name) {
  auto k8snat = get_cube(name);

  return k8snat->delRule();
}

/**
* @brief   Delete dnat by ID
*
* Delete operation of resource: dnat*
*
* @param[in] name ID of name
*
* Responses:
*
*/
void
delete_k8snat_rule_dnat_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();

  return rule->delDnat();
}

/**
* @brief   Delete entry by ID
*
* Delete operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
*
*/
void
delete_k8snat_rule_dnat_entry_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();

  return dnat->delEntry(id);
}

/**
* @brief   Delete entry by ID
*
* Delete operation of resource: entry*
*
* @param[in] name ID of name
*
* Responses:
*
*/
void
delete_k8snat_rule_dnat_entry_list_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();
  dnat->delEntryList();
}

/**
* @brief   Delete masquerade by ID
*
* Delete operation of resource: masquerade*
*
* @param[in] name ID of name
*
* Responses:
*
*/
void
delete_k8snat_rule_masquerade_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();

  return rule->delMasquerade();
}

/**
* @brief   Delete port-forwarding by ID
*
* Delete operation of resource: port-forwarding*
*
* @param[in] name ID of name
*
* Responses:
*
*/
void
delete_k8snat_rule_port_forwarding_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();

  return rule->delPortForwarding();
}

/**
* @brief   Delete entry by ID
*
* Delete operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
*
*/
void
delete_k8snat_rule_port_forwarding_entry_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();

  return portForwarding->delEntry(id);
}

/**
* @brief   Delete entry by ID
*
* Delete operation of resource: entry*
*
* @param[in] name ID of name
*
* Responses:
*
*/
void
delete_k8snat_rule_port_forwarding_entry_list_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  portForwarding->delEntryList();
}

/**
* @brief   Delete snat by ID
*
* Delete operation of resource: snat*
*
* @param[in] name ID of name
*
* Responses:
*
*/
void
delete_k8snat_rule_snat_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();

  return rule->delSnat();
}

/**
* @brief   Delete entry by ID
*
* Delete operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
*
*/
void
delete_k8snat_rule_snat_entry_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();

  return snat->delEntry(id);
}

/**
* @brief   Delete entry by ID
*
* Delete operation of resource: entry*
*
* @param[in] name ID of name
*
* Responses:
*
*/
void
delete_k8snat_rule_snat_entry_list_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();
  snat->delEntryList();
}

/**
* @brief   Read k8snat by ID
*
* Read operation of resource: k8snat*
*
* @param[in] name ID of name
*
* Responses:
* K8snatJsonObject
*/
K8snatJsonObject
read_k8snat_by_id(const std::string &name) {
  return get_cube(name)->toJsonObject();

}

/**
* @brief   Read natting-table by ID
*
* Read operation of resource: natting-table*
*
* @param[in] name ID of name
* @param[in] internalSrc ID of internal-src
* @param[in] internalDst ID of internal-dst
* @param[in] internalSport ID of internal-sport
* @param[in] internalDport ID of internal-dport
* @param[in] proto ID of proto
*
* Responses:
* NattingTableJsonObject
*/
NattingTableJsonObject
read_k8snat_natting_table_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto) {
  auto k8snat = get_cube(name);
  return k8snat->getNattingTable(internalSrc, internalDst, internalSport, internalDport, proto)->toJsonObject();

}

/**
* @brief   Read external-ip by ID
*
* Read operation of resource: external-ip*
*
* @param[in] name ID of name
* @param[in] internalSrc ID of internal-src
* @param[in] internalDst ID of internal-dst
* @param[in] internalSport ID of internal-sport
* @param[in] internalDport ID of internal-dport
* @param[in] proto ID of proto
*
* Responses:
* std::string
*/
std::string
read_k8snat_natting_table_external_ip_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto) {
  auto k8snat = get_cube(name);
  auto nattingTable = k8snat->getNattingTable(internalSrc, internalDst, internalSport, internalDport, proto);
  return nattingTable->getExternalIp();

}

/**
* @brief   Read external-port by ID
*
* Read operation of resource: external-port*
*
* @param[in] name ID of name
* @param[in] internalSrc ID of internal-src
* @param[in] internalDst ID of internal-dst
* @param[in] internalSport ID of internal-sport
* @param[in] internalDport ID of internal-dport
* @param[in] proto ID of proto
*
* Responses:
* uint16_t
*/
uint16_t
read_k8snat_natting_table_external_port_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto) {
  auto k8snat = get_cube(name);
  auto nattingTable = k8snat->getNattingTable(internalSrc, internalDst, internalSport, internalDport, proto);
  return nattingTable->getExternalPort();

}

/**
* @brief   Read natting-table by ID
*
* Read operation of resource: natting-table*
*
* @param[in] name ID of name
*
* Responses:
* std::vector<NattingTableJsonObject>
*/
std::vector<NattingTableJsonObject>
read_k8snat_natting_table_list_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto &&nattingTable = k8snat->getNattingTableList();
  std::vector<NattingTableJsonObject> m;
  for(auto &i : nattingTable)
    m.push_back(i->toJsonObject());
  return m;
}

/**
* @brief   Read originating-rule by ID
*
* Read operation of resource: originating-rule*
*
* @param[in] name ID of name
* @param[in] internalSrc ID of internal-src
* @param[in] internalDst ID of internal-dst
* @param[in] internalSport ID of internal-sport
* @param[in] internalDport ID of internal-dport
* @param[in] proto ID of proto
*
* Responses:
* NattingTableOriginatingRuleEnum
*/
NattingTableOriginatingRuleEnum
read_k8snat_natting_table_originating_rule_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto) {
  auto k8snat = get_cube(name);
  auto nattingTable = k8snat->getNattingTable(internalSrc, internalDst, internalSport, internalDport, proto);
  return nattingTable->getOriginatingRule();

}

/**
* @brief   Read ports by ID
*
* Read operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] portsName ID of ports_name
*
* Responses:
* PortsJsonObject
*/
PortsJsonObject
read_k8snat_ports_by_id(const std::string &name, const std::string &portsName) {
  auto k8snat = get_cube(name);
  return k8snat->getPorts(portsName)->toJsonObject();

}

/**
* @brief   Read ports by ID
*
* Read operation of resource: ports*
*
* @param[in] name ID of name
*
* Responses:
* std::vector<PortsJsonObject>
*/
std::vector<PortsJsonObject>
read_k8snat_ports_list_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto &&ports = k8snat->getPortsList();
  std::vector<PortsJsonObject> m;
  for(auto &i : ports)
    m.push_back(i->toJsonObject());
  return m;
}

/**
* @brief   Read type by ID
*
* Read operation of resource: type*
*
* @param[in] name ID of name
* @param[in] portsName ID of ports_name
*
* Responses:
* PortsTypeEnum
*/
PortsTypeEnum
read_k8snat_ports_type_by_id(const std::string &name, const std::string &portsName) {
  auto k8snat = get_cube(name);
  auto ports = k8snat->getPorts(portsName);
  return ports->getType();

}

/**
* @brief   Read rule by ID
*
* Read operation of resource: rule*
*
* @param[in] name ID of name
*
* Responses:
* RuleJsonObject
*/
RuleJsonObject
read_k8snat_rule_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  return k8snat->getRule()->toJsonObject();

}

/**
* @brief   Read dnat by ID
*
* Read operation of resource: dnat*
*
* @param[in] name ID of name
*
* Responses:
* RuleDnatJsonObject
*/
RuleDnatJsonObject
read_k8snat_rule_dnat_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  return rule->getDnat()->toJsonObject();

}

/**
* @brief   Read entry by ID
*
* Read operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
* RuleDnatEntryJsonObject
*/
RuleDnatEntryJsonObject
read_k8snat_rule_dnat_entry_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();
  return dnat->getEntry(id)->toJsonObject();

}

/**
* @brief   Read external-ip by ID
*
* Read operation of resource: external-ip*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
* std::string
*/
std::string
read_k8snat_rule_dnat_entry_external_ip_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();
  auto entry = dnat->getEntry(id);
  return entry->getExternalIp();

}

/**
* @brief   Read internal-ip by ID
*
* Read operation of resource: internal-ip*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
* std::string
*/
std::string
read_k8snat_rule_dnat_entry_internal_ip_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();
  auto entry = dnat->getEntry(id);
  return entry->getInternalIp();

}

/**
* @brief   Read entry by ID
*
* Read operation of resource: entry*
*
* @param[in] name ID of name
*
* Responses:
* std::vector<RuleDnatEntryJsonObject>
*/
std::vector<RuleDnatEntryJsonObject>
read_k8snat_rule_dnat_entry_list_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();
  auto &&entry = dnat->getEntryList();
  std::vector<RuleDnatEntryJsonObject> m;
  for(auto &i : entry)
    m.push_back(i->toJsonObject());
  return m;
}

/**
* @brief   Read masquerade by ID
*
* Read operation of resource: masquerade*
*
* @param[in] name ID of name
*
* Responses:
* RuleMasqueradeJsonObject
*/
RuleMasqueradeJsonObject
read_k8snat_rule_masquerade_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  return rule->getMasquerade()->toJsonObject();

}

/**
* @brief   Read enabled by ID
*
* Read operation of resource: enabled*
*
* @param[in] name ID of name
*
* Responses:
* bool
*/
bool
read_k8snat_rule_masquerade_enabled_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto masquerade = rule->getMasquerade();
  return masquerade->getEnabled();

}

/**
* @brief   Read port-forwarding by ID
*
* Read operation of resource: port-forwarding*
*
* @param[in] name ID of name
*
* Responses:
* RulePortForwardingJsonObject
*/
RulePortForwardingJsonObject
read_k8snat_rule_port_forwarding_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  return rule->getPortForwarding()->toJsonObject();

}

/**
* @brief   Read entry by ID
*
* Read operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
* RulePortForwardingEntryJsonObject
*/
RulePortForwardingEntryJsonObject
read_k8snat_rule_port_forwarding_entry_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  return portForwarding->getEntry(id)->toJsonObject();

}

/**
* @brief   Read external-ip by ID
*
* Read operation of resource: external-ip*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
* std::string
*/
std::string
read_k8snat_rule_port_forwarding_entry_external_ip_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  auto entry = portForwarding->getEntry(id);
  return entry->getExternalIp();

}

/**
* @brief   Read external-port by ID
*
* Read operation of resource: external-port*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
* uint16_t
*/
uint16_t
read_k8snat_rule_port_forwarding_entry_external_port_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  auto entry = portForwarding->getEntry(id);
  return entry->getExternalPort();

}

/**
* @brief   Read internal-ip by ID
*
* Read operation of resource: internal-ip*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
* std::string
*/
std::string
read_k8snat_rule_port_forwarding_entry_internal_ip_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  auto entry = portForwarding->getEntry(id);
  return entry->getInternalIp();

}

/**
* @brief   Read internal-port by ID
*
* Read operation of resource: internal-port*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
* uint16_t
*/
uint16_t
read_k8snat_rule_port_forwarding_entry_internal_port_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  auto entry = portForwarding->getEntry(id);
  return entry->getInternalPort();

}

/**
* @brief   Read entry by ID
*
* Read operation of resource: entry*
*
* @param[in] name ID of name
*
* Responses:
* std::vector<RulePortForwardingEntryJsonObject>
*/
std::vector<RulePortForwardingEntryJsonObject>
read_k8snat_rule_port_forwarding_entry_list_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  auto &&entry = portForwarding->getEntryList();
  std::vector<RulePortForwardingEntryJsonObject> m;
  for(auto &i : entry)
    m.push_back(i->toJsonObject());
  return m;
}

/**
* @brief   Read proto by ID
*
* Read operation of resource: proto*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
* std::string
*/
std::string
read_k8snat_rule_port_forwarding_entry_proto_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  auto entry = portForwarding->getEntry(id);
  return entry->getProto();

}

/**
* @brief   Read snat by ID
*
* Read operation of resource: snat*
*
* @param[in] name ID of name
*
* Responses:
* RuleSnatJsonObject
*/
RuleSnatJsonObject
read_k8snat_rule_snat_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  return rule->getSnat()->toJsonObject();

}

/**
* @brief   Read entry by ID
*
* Read operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
* RuleSnatEntryJsonObject
*/
RuleSnatEntryJsonObject
read_k8snat_rule_snat_entry_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();
  return snat->getEntry(id)->toJsonObject();

}

/**
* @brief   Read external-ip by ID
*
* Read operation of resource: external-ip*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
* std::string
*/
std::string
read_k8snat_rule_snat_entry_external_ip_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();
  auto entry = snat->getEntry(id);
  return entry->getExternalIp();

}

/**
* @brief   Read internal-net by ID
*
* Read operation of resource: internal-net*
*
* @param[in] name ID of name
* @param[in] id ID of id
*
* Responses:
* std::string
*/
std::string
read_k8snat_rule_snat_entry_internal_net_by_id(const std::string &name, const uint32_t &id) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();
  auto entry = snat->getEntry(id);
  return entry->getInternalNet();

}

/**
* @brief   Read entry by ID
*
* Read operation of resource: entry*
*
* @param[in] name ID of name
*
* Responses:
* std::vector<RuleSnatEntryJsonObject>
*/
std::vector<RuleSnatEntryJsonObject>
read_k8snat_rule_snat_entry_list_by_id(const std::string &name) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();
  auto &&entry = snat->getEntryList();
  std::vector<RuleSnatEntryJsonObject> m;
  for(auto &i : entry)
    m.push_back(i->toJsonObject());
  return m;
}

/**
* @brief   Replace natting-table by ID
*
* Replace operation of resource: natting-table*
*
* @param[in] name ID of name
* @param[in] internalSrc ID of internal-src
* @param[in] internalDst ID of internal-dst
* @param[in] internalSport ID of internal-sport
* @param[in] internalDport ID of internal-dport
* @param[in] proto ID of proto
* @param[in] value natting-tablebody object
*
* Responses:
*
*/
void
replace_k8snat_natting_table_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const NattingTableJsonObject &value) {
  auto k8snat = get_cube(name);

  return k8snat->replaceNattingTable(internalSrc, internalDst, internalSport, internalDport, proto, value);
}

/**
* @brief   Replace natting-table by ID
*
* Replace operation of resource: natting-table*
*
* @param[in] name ID of name
* @param[in] value natting-tablebody object
*
* Responses:
*
*/
void
replace_k8snat_natting_table_list_by_id(const std::string &name, const std::vector<NattingTableJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}

/**
* @brief   Replace ports by ID
*
* Replace operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] portsName ID of ports_name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
replace_k8snat_ports_by_id(const std::string &name, const std::string &portsName, const PortsJsonObject &value) {
  auto k8snat = get_cube(name);

  return k8snat->replacePorts(portsName, value);
}

/**
* @brief   Replace ports by ID
*
* Replace operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
replace_k8snat_ports_list_by_id(const std::string &name, const std::vector<PortsJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}

/**
* @brief   Replace rule by ID
*
* Replace operation of resource: rule*
*
* @param[in] name ID of name
* @param[in] value rulebody object
*
* Responses:
*
*/
void
replace_k8snat_rule_by_id(const std::string &name, const RuleJsonObject &value) {
  auto k8snat = get_cube(name);

  return k8snat->replaceRule(value);
}

/**
* @brief   Replace dnat by ID
*
* Replace operation of resource: dnat*
*
* @param[in] name ID of name
* @param[in] value dnatbody object
*
* Responses:
*
*/
void
replace_k8snat_rule_dnat_by_id(const std::string &name, const RuleDnatJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();

  return rule->replaceDnat(value);
}

/**
* @brief   Replace entry by ID
*
* Replace operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value entrybody object
*
* Responses:
*
*/
void
replace_k8snat_rule_dnat_entry_by_id(const std::string &name, const uint32_t &id, const RuleDnatEntryJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();

  return dnat->replaceEntry(id, value);
}

/**
* @brief   Replace entry by ID
*
* Replace operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] value entrybody object
*
* Responses:
*
*/
void
replace_k8snat_rule_dnat_entry_list_by_id(const std::string &name, const std::vector<RuleDnatEntryJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}

/**
* @brief   Replace masquerade by ID
*
* Replace operation of resource: masquerade*
*
* @param[in] name ID of name
* @param[in] value masqueradebody object
*
* Responses:
*
*/
void
replace_k8snat_rule_masquerade_by_id(const std::string &name, const RuleMasqueradeJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();

  return rule->replaceMasquerade(value);
}

/**
* @brief   Replace port-forwarding by ID
*
* Replace operation of resource: port-forwarding*
*
* @param[in] name ID of name
* @param[in] value port-forwardingbody object
*
* Responses:
*
*/
void
replace_k8snat_rule_port_forwarding_by_id(const std::string &name, const RulePortForwardingJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();

  return rule->replacePortForwarding(value);
}

/**
* @brief   Replace entry by ID
*
* Replace operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value entrybody object
*
* Responses:
*
*/
void
replace_k8snat_rule_port_forwarding_entry_by_id(const std::string &name, const uint32_t &id, const RulePortForwardingEntryJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();

  return portForwarding->replaceEntry(id, value);
}

/**
* @brief   Replace entry by ID
*
* Replace operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] value entrybody object
*
* Responses:
*
*/
void
replace_k8snat_rule_port_forwarding_entry_list_by_id(const std::string &name, const std::vector<RulePortForwardingEntryJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}

/**
* @brief   Replace snat by ID
*
* Replace operation of resource: snat*
*
* @param[in] name ID of name
* @param[in] value snatbody object
*
* Responses:
*
*/
void
replace_k8snat_rule_snat_by_id(const std::string &name, const RuleSnatJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();

  return rule->replaceSnat(value);
}

/**
* @brief   Replace entry by ID
*
* Replace operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value entrybody object
*
* Responses:
*
*/
void
replace_k8snat_rule_snat_entry_by_id(const std::string &name, const uint32_t &id, const RuleSnatEntryJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();

  return snat->replaceEntry(id, value);
}

/**
* @brief   Replace entry by ID
*
* Replace operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] value entrybody object
*
* Responses:
*
*/
void
replace_k8snat_rule_snat_entry_list_by_id(const std::string &name, const std::vector<RuleSnatEntryJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}

/**
* @brief   Update k8snat by ID
*
* Update operation of resource: k8snat*
*
* @param[in] name ID of name
* @param[in] value k8snatbody object
*
* Responses:
*
*/
void
update_k8snat_by_id(const std::string &name, const K8snatJsonObject &value) {
  auto k8snat = get_cube(name);

  return k8snat->update(value);
}

/**
* @brief   Update k8snat by ID
*
* Update operation of resource: k8snat*
*
* @param[in] value k8snatbody object
*
* Responses:
*
*/
void
update_k8snat_list_by_id(const std::vector<K8snatJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}

/**
* @brief   Update natting-table by ID
*
* Update operation of resource: natting-table*
*
* @param[in] name ID of name
* @param[in] internalSrc ID of internal-src
* @param[in] internalDst ID of internal-dst
* @param[in] internalSport ID of internal-sport
* @param[in] internalDport ID of internal-dport
* @param[in] proto ID of proto
* @param[in] value natting-tablebody object
*
* Responses:
*
*/
void
update_k8snat_natting_table_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const NattingTableJsonObject &value) {
  auto k8snat = get_cube(name);
  auto nattingTable = k8snat->getNattingTable(internalSrc, internalDst, internalSport, internalDport, proto);

  return nattingTable->update(value);
}

/**
* @brief   Update external-ip by ID
*
* Update operation of resource: external-ip*
*
* @param[in] name ID of name
* @param[in] internalSrc ID of internal-src
* @param[in] internalDst ID of internal-dst
* @param[in] internalSport ID of internal-sport
* @param[in] internalDport ID of internal-dport
* @param[in] proto ID of proto
* @param[in] value Translated IP address
*
* Responses:
*
*/
void
update_k8snat_natting_table_external_ip_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const std::string &value) {
  auto k8snat = get_cube(name);
  auto nattingTable = k8snat->getNattingTable(internalSrc, internalDst, internalSport, internalDport, proto);

  return nattingTable->setExternalIp(value);
}

/**
* @brief   Update external-port by ID
*
* Update operation of resource: external-port*
*
* @param[in] name ID of name
* @param[in] internalSrc ID of internal-src
* @param[in] internalDst ID of internal-dst
* @param[in] internalSport ID of internal-sport
* @param[in] internalDport ID of internal-dport
* @param[in] proto ID of proto
* @param[in] value Translated L4 port number
*
* Responses:
*
*/
void
update_k8snat_natting_table_external_port_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const uint16_t &value) {
  auto k8snat = get_cube(name);
  auto nattingTable = k8snat->getNattingTable(internalSrc, internalDst, internalSport, internalDport, proto);

  return nattingTable->setExternalPort(value);
}

/**
* @brief   Update natting-table by ID
*
* Update operation of resource: natting-table*
*
* @param[in] name ID of name
* @param[in] value natting-tablebody object
*
* Responses:
*
*/
void
update_k8snat_natting_table_list_by_id(const std::string &name, const std::vector<NattingTableJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}

/**
* @brief   Update originating-rule by ID
*
* Update operation of resource: originating-rule*
*
* @param[in] name ID of name
* @param[in] internalSrc ID of internal-src
* @param[in] internalDst ID of internal-dst
* @param[in] internalSport ID of internal-sport
* @param[in] internalDport ID of internal-dport
* @param[in] proto ID of proto
* @param[in] value The set of rules that created this mapping
*
* Responses:
*
*/
void
update_k8snat_natting_table_originating_rule_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const NattingTableOriginatingRuleEnum &value) {
  auto k8snat = get_cube(name);
  auto nattingTable = k8snat->getNattingTable(internalSrc, internalDst, internalSport, internalDport, proto);

  return nattingTable->setOriginatingRule(value);
}

/**
* @brief   Update ports by ID
*
* Update operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] portsName ID of ports_name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
update_k8snat_ports_by_id(const std::string &name, const std::string &portsName, const PortsJsonObject &value) {
  auto k8snat = get_cube(name);
  auto ports = k8snat->getPorts(portsName);

  return ports->update(value);
}

/**
* @brief   Update ports by ID
*
* Update operation of resource: ports*
*
* @param[in] name ID of name
* @param[in] value portsbody object
*
* Responses:
*
*/
void
update_k8snat_ports_list_by_id(const std::string &name, const std::vector<PortsJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}

/**
* @brief   Update type by ID
*
* Update operation of resource: type*
*
* @param[in] name ID of name
* @param[in] portsName ID of ports_name
* @param[in] value Type of the k8sNAT port (e.g. FRONTEND or BACKEND)
*
* Responses:
*
*/
void
update_k8snat_ports_type_by_id(const std::string &name, const std::string &portsName, const PortsTypeEnum &value) {
  auto k8snat = get_cube(name);
  auto ports = k8snat->getPorts(portsName);

  return ports->setType(value);
}

/**
* @brief   Update rule by ID
*
* Update operation of resource: rule*
*
* @param[in] name ID of name
* @param[in] value rulebody object
*
* Responses:
*
*/
void
update_k8snat_rule_by_id(const std::string &name, const RuleJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();

  return rule->update(value);
}

/**
* @brief   Update dnat by ID
*
* Update operation of resource: dnat*
*
* @param[in] name ID of name
* @param[in] value dnatbody object
*
* Responses:
*
*/
void
update_k8snat_rule_dnat_by_id(const std::string &name, const RuleDnatJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();

  return dnat->update(value);
}

/**
* @brief   Update entry by ID
*
* Update operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value entrybody object
*
* Responses:
*
*/
void
update_k8snat_rule_dnat_entry_by_id(const std::string &name, const uint32_t &id, const RuleDnatEntryJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();
  auto entry = dnat->getEntry(id);

  return entry->update(value);
}

/**
* @brief   Update external-ip by ID
*
* Update operation of resource: external-ip*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value External destination IP address
*
* Responses:
*
*/
void
update_k8snat_rule_dnat_entry_external_ip_by_id(const std::string &name, const uint32_t &id, const std::string &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();
  auto entry = dnat->getEntry(id);

  return entry->setExternalIp(value);
}

/**
* @brief   Update internal-ip by ID
*
* Update operation of resource: internal-ip*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value Internal destination IP address
*
* Responses:
*
*/
void
update_k8snat_rule_dnat_entry_internal_ip_by_id(const std::string &name, const uint32_t &id, const std::string &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto dnat = rule->getDnat();
  auto entry = dnat->getEntry(id);

  return entry->setInternalIp(value);
}

/**
* @brief   Update entry by ID
*
* Update operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] value entrybody object
*
* Responses:
*
*/
void
update_k8snat_rule_dnat_entry_list_by_id(const std::string &name, const std::vector<RuleDnatEntryJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}

/**
* @brief   Update masquerade by ID
*
* Update operation of resource: masquerade*
*
* @param[in] name ID of name
* @param[in] value masqueradebody object
*
* Responses:
*
*/
void
update_k8snat_rule_masquerade_by_id(const std::string &name, const RuleMasqueradeJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto masquerade = rule->getMasquerade();

  return masquerade->update(value);
}

/**
* @brief   Update enabled by ID
*
* Update operation of resource: enabled*
*
* @param[in] name ID of name
* @param[in] value enabledbody object
*
* Responses:
*
*/
void
update_k8snat_rule_masquerade_enabled_by_id(const std::string &name, const bool &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto masquerade = rule->getMasquerade();

  return masquerade->setEnabled(value);
}

/**
* @brief   Update port-forwarding by ID
*
* Update operation of resource: port-forwarding*
*
* @param[in] name ID of name
* @param[in] value port-forwardingbody object
*
* Responses:
*
*/
void
update_k8snat_rule_port_forwarding_by_id(const std::string &name, const RulePortForwardingJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();

  return portForwarding->update(value);
}

/**
* @brief   Update entry by ID
*
* Update operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value entrybody object
*
* Responses:
*
*/
void
update_k8snat_rule_port_forwarding_entry_by_id(const std::string &name, const uint32_t &id, const RulePortForwardingEntryJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  auto entry = portForwarding->getEntry(id);

  return entry->update(value);
}

/**
* @brief   Update external-ip by ID
*
* Update operation of resource: external-ip*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value External destination IP address
*
* Responses:
*
*/
void
update_k8snat_rule_port_forwarding_entry_external_ip_by_id(const std::string &name, const uint32_t &id, const std::string &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  auto entry = portForwarding->getEntry(id);

  return entry->setExternalIp(value);
}

/**
* @brief   Update external-port by ID
*
* Update operation of resource: external-port*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value External destination L4 port
*
* Responses:
*
*/
void
update_k8snat_rule_port_forwarding_entry_external_port_by_id(const std::string &name, const uint32_t &id, const uint16_t &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  auto entry = portForwarding->getEntry(id);

  return entry->setExternalPort(value);
}

/**
* @brief   Update internal-ip by ID
*
* Update operation of resource: internal-ip*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value Internal destination IP address
*
* Responses:
*
*/
void
update_k8snat_rule_port_forwarding_entry_internal_ip_by_id(const std::string &name, const uint32_t &id, const std::string &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  auto entry = portForwarding->getEntry(id);

  return entry->setInternalIp(value);
}

/**
* @brief   Update internal-port by ID
*
* Update operation of resource: internal-port*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value Internal destination L4 port
*
* Responses:
*
*/
void
update_k8snat_rule_port_forwarding_entry_internal_port_by_id(const std::string &name, const uint32_t &id, const uint16_t &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  auto entry = portForwarding->getEntry(id);

  return entry->setInternalPort(value);
}

/**
* @brief   Update entry by ID
*
* Update operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] value entrybody object
*
* Responses:
*
*/
void
update_k8snat_rule_port_forwarding_entry_list_by_id(const std::string &name, const std::vector<RulePortForwardingEntryJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}

/**
* @brief   Update proto by ID
*
* Update operation of resource: proto*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value L4 protocol (TCP, UDP, ALL)
*
* Responses:
*
*/
void
update_k8snat_rule_port_forwarding_entry_proto_by_id(const std::string &name, const uint32_t &id, const std::string &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto portForwarding = rule->getPortForwarding();
  auto entry = portForwarding->getEntry(id);

  return entry->setProto(value);
}

/**
* @brief   Update snat by ID
*
* Update operation of resource: snat*
*
* @param[in] name ID of name
* @param[in] value snatbody object
*
* Responses:
*
*/
void
update_k8snat_rule_snat_by_id(const std::string &name, const RuleSnatJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();

  return snat->update(value);
}

/**
* @brief   Update entry by ID
*
* Update operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value entrybody object
*
* Responses:
*
*/
void
update_k8snat_rule_snat_entry_by_id(const std::string &name, const uint32_t &id, const RuleSnatEntryJsonObject &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();
  auto entry = snat->getEntry(id);

  return entry->update(value);
}

/**
* @brief   Update external-ip by ID
*
* Update operation of resource: external-ip*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value Natted source IP address
*
* Responses:
*
*/
void
update_k8snat_rule_snat_entry_external_ip_by_id(const std::string &name, const uint32_t &id, const std::string &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();
  auto entry = snat->getEntry(id);

  return entry->setExternalIp(value);
}

/**
* @brief   Update internal-net by ID
*
* Update operation of resource: internal-net*
*
* @param[in] name ID of name
* @param[in] id ID of id
* @param[in] value Internal IP address (or subnet)
*
* Responses:
*
*/
void
update_k8snat_rule_snat_entry_internal_net_by_id(const std::string &name, const uint32_t &id, const std::string &value) {
  auto k8snat = get_cube(name);
  auto rule = k8snat->getRule();
  auto snat = rule->getSnat();
  auto entry = snat->getEntry(id);

  return entry->setInternalNet(value);
}

/**
* @brief   Update entry by ID
*
* Update operation of resource: entry*
*
* @param[in] name ID of name
* @param[in] value entrybody object
*
* Responses:
*
*/
void
update_k8snat_rule_snat_entry_list_by_id(const std::string &name, const std::vector<RuleSnatEntryJsonObject> &value) {
  throw std::runtime_error("Method not supported");
}



/*
 * help related
 */

std::vector<nlohmann::fifo_map<std::string, std::string>> read_k8snat_natting_table_list_by_id_get_list(const std::string &name) {
  std::vector<nlohmann::fifo_map<std::string, std::string>> r;
  auto &&k8snat = get_cube(name);

  auto &&nattingTable = k8snat->getNattingTableList();
  for(auto &i : nattingTable) {
    nlohmann::fifo_map<std::string, std::string> keys;

    keys["internalSrc"] = i->getInternalSrc();
    keys["internalDst"] = i->getInternalDst();
    keys["internalSport"] = std::to_string(i->getInternalSport());
    keys["internalDport"] = std::to_string(i->getInternalDport());
    keys["proto"] = i->getProto();

    r.push_back(keys);
  }
  return r;
}

std::vector<nlohmann::fifo_map<std::string, std::string>> read_k8snat_ports_list_by_id_get_list(const std::string &name) {
  std::vector<nlohmann::fifo_map<std::string, std::string>> r;
  auto &&k8snat = get_cube(name);

  auto &&ports = k8snat->getPortsList();
  for(auto &i : ports) {
    nlohmann::fifo_map<std::string, std::string> keys;

    keys["name"] = i->getName();

    r.push_back(keys);
  }
  return r;
}

std::vector<nlohmann::fifo_map<std::string, std::string>> read_k8snat_rule_dnat_entry_list_by_id_get_list(const std::string &name) {
  std::vector<nlohmann::fifo_map<std::string, std::string>> r;
  auto &&k8snat = get_cube(name);
  auto &&rule = k8snat->getRule();
  auto &&dnat = rule->getDnat();

  auto &&entry = dnat->getEntryList();
  for(auto &i : entry) {
    nlohmann::fifo_map<std::string, std::string> keys;

    keys["id"] = std::to_string(i->getId());

    r.push_back(keys);
  }
  return r;
}

std::vector<nlohmann::fifo_map<std::string, std::string>> read_k8snat_rule_port_forwarding_entry_list_by_id_get_list(const std::string &name) {
  std::vector<nlohmann::fifo_map<std::string, std::string>> r;
  auto &&k8snat = get_cube(name);
  auto &&rule = k8snat->getRule();
  auto &&portForwarding = rule->getPortForwarding();

  auto &&entry = portForwarding->getEntryList();
  for(auto &i : entry) {
    nlohmann::fifo_map<std::string, std::string> keys;

    keys["id"] = std::to_string(i->getId());

    r.push_back(keys);
  }
  return r;
}

std::vector<nlohmann::fifo_map<std::string, std::string>> read_k8snat_rule_snat_entry_list_by_id_get_list(const std::string &name) {
  std::vector<nlohmann::fifo_map<std::string, std::string>> r;
  auto &&k8snat = get_cube(name);
  auto &&rule = k8snat->getRule();
  auto &&snat = rule->getSnat();

  auto &&entry = snat->getEntryList();
  for(auto &i : entry) {
    nlohmann::fifo_map<std::string, std::string> keys;

    keys["id"] = std::to_string(i->getId());

    r.push_back(keys);
  }
  return r;
}


}

}
}
}

