/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* K8snatApiImpl.h
*
*
*/

#pragma once


#include <memory>
#include <map>
#include <mutex>
#include "../K8snat.h"

#include "K8snatJsonObject.h"
#include "NattingTableJsonObject.h"
#include "PortsJsonObject.h"
#include "RuleJsonObject.h"
#include "RuleDnatJsonObject.h"
#include "RuleDnatAppendInputJsonObject.h"
#include "RuleDnatAppendOutputJsonObject.h"
#include "RuleDnatEntryJsonObject.h"
#include "RuleMasqueradeJsonObject.h"
#include "RuleMasqueradeDisableOutputJsonObject.h"
#include "RuleMasqueradeEnableOutputJsonObject.h"
#include "RulePortForwardingJsonObject.h"
#include "RulePortForwardingAppendInputJsonObject.h"
#include "RulePortForwardingAppendOutputJsonObject.h"
#include "RulePortForwardingEntryJsonObject.h"
#include "RuleSnatJsonObject.h"
#include "RuleSnatAppendInputJsonObject.h"
#include "RuleSnatAppendOutputJsonObject.h"
#include "RuleSnatEntryJsonObject.h"
#include <vector>

namespace polycube {
namespace service {
namespace api {

using namespace polycube::service::model;

namespace K8snatApiImpl {
  void create_k8snat_by_id(const std::string &name, const K8snatJsonObject &value);
  void create_k8snat_natting_table_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const NattingTableJsonObject &value);
  void create_k8snat_natting_table_list_by_id(const std::string &name, const std::vector<NattingTableJsonObject> &value);
  void create_k8snat_ports_by_id(const std::string &name, const std::string &portsName, const PortsJsonObject &value);
  void create_k8snat_ports_list_by_id(const std::string &name, const std::vector<PortsJsonObject> &value);
  void create_k8snat_rule_by_id(const std::string &name, const RuleJsonObject &value);
  RuleDnatAppendOutputJsonObject create_k8snat_rule_dnat_append_by_id(const std::string &name, const RuleDnatAppendInputJsonObject &value);
  void create_k8snat_rule_dnat_by_id(const std::string &name, const RuleDnatJsonObject &value);
  void create_k8snat_rule_dnat_entry_by_id(const std::string &name, const uint32_t &id, const RuleDnatEntryJsonObject &value);
  void create_k8snat_rule_dnat_entry_list_by_id(const std::string &name, const std::vector<RuleDnatEntryJsonObject> &value);
  void create_k8snat_rule_masquerade_by_id(const std::string &name, const RuleMasqueradeJsonObject &value);
  RuleMasqueradeDisableOutputJsonObject create_k8snat_rule_masquerade_disable_by_id(const std::string &name);
  RuleMasqueradeEnableOutputJsonObject create_k8snat_rule_masquerade_enable_by_id(const std::string &name);
  RulePortForwardingAppendOutputJsonObject create_k8snat_rule_port_forwarding_append_by_id(const std::string &name, const RulePortForwardingAppendInputJsonObject &value);
  void create_k8snat_rule_port_forwarding_by_id(const std::string &name, const RulePortForwardingJsonObject &value);
  void create_k8snat_rule_port_forwarding_entry_by_id(const std::string &name, const uint32_t &id, const RulePortForwardingEntryJsonObject &value);
  void create_k8snat_rule_port_forwarding_entry_list_by_id(const std::string &name, const std::vector<RulePortForwardingEntryJsonObject> &value);
  RuleSnatAppendOutputJsonObject create_k8snat_rule_snat_append_by_id(const std::string &name, const RuleSnatAppendInputJsonObject &value);
  void create_k8snat_rule_snat_by_id(const std::string &name, const RuleSnatJsonObject &value);
  void create_k8snat_rule_snat_entry_by_id(const std::string &name, const uint32_t &id, const RuleSnatEntryJsonObject &value);
  void create_k8snat_rule_snat_entry_list_by_id(const std::string &name, const std::vector<RuleSnatEntryJsonObject> &value);
  void delete_k8snat_by_id(const std::string &name);
  void delete_k8snat_natting_table_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto);
  void delete_k8snat_natting_table_list_by_id(const std::string &name);
  void delete_k8snat_ports_by_id(const std::string &name, const std::string &portsName);
  void delete_k8snat_ports_list_by_id(const std::string &name);
  void delete_k8snat_rule_by_id(const std::string &name);
  void delete_k8snat_rule_dnat_by_id(const std::string &name);
  void delete_k8snat_rule_dnat_entry_by_id(const std::string &name, const uint32_t &id);
  void delete_k8snat_rule_dnat_entry_list_by_id(const std::string &name);
  void delete_k8snat_rule_masquerade_by_id(const std::string &name);
  void delete_k8snat_rule_port_forwarding_by_id(const std::string &name);
  void delete_k8snat_rule_port_forwarding_entry_by_id(const std::string &name, const uint32_t &id);
  void delete_k8snat_rule_port_forwarding_entry_list_by_id(const std::string &name);
  void delete_k8snat_rule_snat_by_id(const std::string &name);
  void delete_k8snat_rule_snat_entry_by_id(const std::string &name, const uint32_t &id);
  void delete_k8snat_rule_snat_entry_list_by_id(const std::string &name);
  K8snatJsonObject read_k8snat_by_id(const std::string &name);
  std::vector<K8snatJsonObject> read_k8snat_list_by_id();
  NattingTableJsonObject read_k8snat_natting_table_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto);
  std::string read_k8snat_natting_table_external_ip_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto);
  uint16_t read_k8snat_natting_table_external_port_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto);
  std::vector<NattingTableJsonObject> read_k8snat_natting_table_list_by_id(const std::string &name);
  NattingTableOriginatingRuleEnum read_k8snat_natting_table_originating_rule_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto);
  PortsJsonObject read_k8snat_ports_by_id(const std::string &name, const std::string &portsName);
  std::vector<PortsJsonObject> read_k8snat_ports_list_by_id(const std::string &name);
  PortsTypeEnum read_k8snat_ports_type_by_id(const std::string &name, const std::string &portsName);
  RuleJsonObject read_k8snat_rule_by_id(const std::string &name);
  RuleDnatJsonObject read_k8snat_rule_dnat_by_id(const std::string &name);
  RuleDnatEntryJsonObject read_k8snat_rule_dnat_entry_by_id(const std::string &name, const uint32_t &id);
  std::string read_k8snat_rule_dnat_entry_external_ip_by_id(const std::string &name, const uint32_t &id);
  std::string read_k8snat_rule_dnat_entry_internal_ip_by_id(const std::string &name, const uint32_t &id);
  std::vector<RuleDnatEntryJsonObject> read_k8snat_rule_dnat_entry_list_by_id(const std::string &name);
  RuleMasqueradeJsonObject read_k8snat_rule_masquerade_by_id(const std::string &name);
  bool read_k8snat_rule_masquerade_enabled_by_id(const std::string &name);
  RulePortForwardingJsonObject read_k8snat_rule_port_forwarding_by_id(const std::string &name);
  RulePortForwardingEntryJsonObject read_k8snat_rule_port_forwarding_entry_by_id(const std::string &name, const uint32_t &id);
  std::string read_k8snat_rule_port_forwarding_entry_external_ip_by_id(const std::string &name, const uint32_t &id);
  uint16_t read_k8snat_rule_port_forwarding_entry_external_port_by_id(const std::string &name, const uint32_t &id);
  std::string read_k8snat_rule_port_forwarding_entry_internal_ip_by_id(const std::string &name, const uint32_t &id);
  uint16_t read_k8snat_rule_port_forwarding_entry_internal_port_by_id(const std::string &name, const uint32_t &id);
  std::vector<RulePortForwardingEntryJsonObject> read_k8snat_rule_port_forwarding_entry_list_by_id(const std::string &name);
  std::string read_k8snat_rule_port_forwarding_entry_proto_by_id(const std::string &name, const uint32_t &id);
  RuleSnatJsonObject read_k8snat_rule_snat_by_id(const std::string &name);
  RuleSnatEntryJsonObject read_k8snat_rule_snat_entry_by_id(const std::string &name, const uint32_t &id);
  std::string read_k8snat_rule_snat_entry_external_ip_by_id(const std::string &name, const uint32_t &id);
  std::string read_k8snat_rule_snat_entry_internal_net_by_id(const std::string &name, const uint32_t &id);
  std::vector<RuleSnatEntryJsonObject> read_k8snat_rule_snat_entry_list_by_id(const std::string &name);
  void replace_k8snat_by_id(const std::string &name, const K8snatJsonObject &value);
  void replace_k8snat_natting_table_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const NattingTableJsonObject &value);
  void replace_k8snat_natting_table_list_by_id(const std::string &name, const std::vector<NattingTableJsonObject> &value);
  void replace_k8snat_ports_by_id(const std::string &name, const std::string &portsName, const PortsJsonObject &value);
  void replace_k8snat_ports_list_by_id(const std::string &name, const std::vector<PortsJsonObject> &value);
  void replace_k8snat_rule_by_id(const std::string &name, const RuleJsonObject &value);
  void replace_k8snat_rule_dnat_by_id(const std::string &name, const RuleDnatJsonObject &value);
  void replace_k8snat_rule_dnat_entry_by_id(const std::string &name, const uint32_t &id, const RuleDnatEntryJsonObject &value);
  void replace_k8snat_rule_dnat_entry_list_by_id(const std::string &name, const std::vector<RuleDnatEntryJsonObject> &value);
  void replace_k8snat_rule_masquerade_by_id(const std::string &name, const RuleMasqueradeJsonObject &value);
  void replace_k8snat_rule_port_forwarding_by_id(const std::string &name, const RulePortForwardingJsonObject &value);
  void replace_k8snat_rule_port_forwarding_entry_by_id(const std::string &name, const uint32_t &id, const RulePortForwardingEntryJsonObject &value);
  void replace_k8snat_rule_port_forwarding_entry_list_by_id(const std::string &name, const std::vector<RulePortForwardingEntryJsonObject> &value);
  void replace_k8snat_rule_snat_by_id(const std::string &name, const RuleSnatJsonObject &value);
  void replace_k8snat_rule_snat_entry_by_id(const std::string &name, const uint32_t &id, const RuleSnatEntryJsonObject &value);
  void replace_k8snat_rule_snat_entry_list_by_id(const std::string &name, const std::vector<RuleSnatEntryJsonObject> &value);
  void update_k8snat_by_id(const std::string &name, const K8snatJsonObject &value);
  void update_k8snat_list_by_id(const std::vector<K8snatJsonObject> &value);
  void update_k8snat_natting_table_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const NattingTableJsonObject &value);
  void update_k8snat_natting_table_external_ip_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const std::string &value);
  void update_k8snat_natting_table_external_port_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const uint16_t &value);
  void update_k8snat_natting_table_list_by_id(const std::string &name, const std::vector<NattingTableJsonObject> &value);
  void update_k8snat_natting_table_originating_rule_by_id(const std::string &name, const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const NattingTableOriginatingRuleEnum &value);
  void update_k8snat_ports_by_id(const std::string &name, const std::string &portsName, const PortsJsonObject &value);
  void update_k8snat_ports_list_by_id(const std::string &name, const std::vector<PortsJsonObject> &value);
  void update_k8snat_ports_type_by_id(const std::string &name, const std::string &portsName, const PortsTypeEnum &value);
  void update_k8snat_rule_by_id(const std::string &name, const RuleJsonObject &value);
  void update_k8snat_rule_dnat_by_id(const std::string &name, const RuleDnatJsonObject &value);
  void update_k8snat_rule_dnat_entry_by_id(const std::string &name, const uint32_t &id, const RuleDnatEntryJsonObject &value);
  void update_k8snat_rule_dnat_entry_external_ip_by_id(const std::string &name, const uint32_t &id, const std::string &value);
  void update_k8snat_rule_dnat_entry_internal_ip_by_id(const std::string &name, const uint32_t &id, const std::string &value);
  void update_k8snat_rule_dnat_entry_list_by_id(const std::string &name, const std::vector<RuleDnatEntryJsonObject> &value);
  void update_k8snat_rule_masquerade_by_id(const std::string &name, const RuleMasqueradeJsonObject &value);
  void update_k8snat_rule_masquerade_enabled_by_id(const std::string &name, const bool &value);
  void update_k8snat_rule_port_forwarding_by_id(const std::string &name, const RulePortForwardingJsonObject &value);
  void update_k8snat_rule_port_forwarding_entry_by_id(const std::string &name, const uint32_t &id, const RulePortForwardingEntryJsonObject &value);
  void update_k8snat_rule_port_forwarding_entry_external_ip_by_id(const std::string &name, const uint32_t &id, const std::string &value);
  void update_k8snat_rule_port_forwarding_entry_external_port_by_id(const std::string &name, const uint32_t &id, const uint16_t &value);
  void update_k8snat_rule_port_forwarding_entry_internal_ip_by_id(const std::string &name, const uint32_t &id, const std::string &value);
  void update_k8snat_rule_port_forwarding_entry_internal_port_by_id(const std::string &name, const uint32_t &id, const uint16_t &value);
  void update_k8snat_rule_port_forwarding_entry_list_by_id(const std::string &name, const std::vector<RulePortForwardingEntryJsonObject> &value);
  void update_k8snat_rule_port_forwarding_entry_proto_by_id(const std::string &name, const uint32_t &id, const std::string &value);
  void update_k8snat_rule_snat_by_id(const std::string &name, const RuleSnatJsonObject &value);
  void update_k8snat_rule_snat_entry_by_id(const std::string &name, const uint32_t &id, const RuleSnatEntryJsonObject &value);
  void update_k8snat_rule_snat_entry_external_ip_by_id(const std::string &name, const uint32_t &id, const std::string &value);
  void update_k8snat_rule_snat_entry_internal_net_by_id(const std::string &name, const uint32_t &id, const std::string &value);
  void update_k8snat_rule_snat_entry_list_by_id(const std::string &name, const std::vector<RuleSnatEntryJsonObject> &value);

  /* help related */
  std::vector<nlohmann::fifo_map<std::string, std::string>> read_k8snat_list_by_id_get_list();
  std::vector<nlohmann::fifo_map<std::string, std::string>> read_k8snat_natting_table_list_by_id_get_list(const std::string &name);
  std::vector<nlohmann::fifo_map<std::string, std::string>> read_k8snat_ports_list_by_id_get_list(const std::string &name);
  std::vector<nlohmann::fifo_map<std::string, std::string>> read_k8snat_rule_dnat_entry_list_by_id_get_list(const std::string &name);
  std::vector<nlohmann::fifo_map<std::string, std::string>> read_k8snat_rule_port_forwarding_entry_list_by_id_get_list(const std::string &name);
  std::vector<nlohmann::fifo_map<std::string, std::string>> read_k8snat_rule_snat_entry_list_by_id_get_list(const std::string &name);

}
}
}
}

