/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

#include "api/K8snatApiImpl.h"
#include "../datamodel/k8snat.h" // generated from datamodel

#define SERVICE_PYANG_GIT ""
#define SERVICE_SWAGGER_CODEGEN_GIT "GIT_REPO_ID"

#include <polycube/services/shared_library.h>

extern "C" const char *data_model() {
  return k8snat_datamodel.c_str();
}
