/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "Ports.h"
#include "K8snat.h"


Ports::Ports(polycube::service::Cube<Ports> &parent,
    std::shared_ptr<polycube::service::PortIface> port,
    const PortsJsonObject &conf)
    : PortsBase(parent, port) {
    port_type_ = conf.getType();
}

Ports::~Ports() {}

PortsTypeEnum Ports::getType() {
  throw std::runtime_error("Ports::getType: Method not implemented");
}

void Ports::setType(const PortsTypeEnum &value) {
  throw std::runtime_error("Ports::setType: Method not implemented");
}


