/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "RuleSnatEntry.h"
#include "K8snat.h"


RuleSnatEntry::RuleSnatEntry(RuleSnat &parent, const RuleSnatEntryJsonObject &conf)
    : RuleSnatEntryBase(parent) {
    setInternalNet(conf.getInternalNet());
    setExternalIp(conf.getExternalIp());
}

RuleSnatEntry::~RuleSnatEntry() {}

uint32_t RuleSnatEntry::getId() {
  throw std::runtime_error("RuleSnatEntry::getId: Method not implemented");
}

std::string RuleSnatEntry::getInternalNet() {
  throw std::runtime_error("RuleSnatEntry::getInternalNet: Method not implemented");
}

void RuleSnatEntry::setInternalNet(const std::string &value) {
  throw std::runtime_error("RuleSnatEntry::setInternalNet: Method not implemented");
}

std::string RuleSnatEntry::getExternalIp() {
  throw std::runtime_error("RuleSnatEntry::getExternalIp: Method not implemented");
}

void RuleSnatEntry::setExternalIp(const std::string &value) {
  throw std::runtime_error("RuleSnatEntry::setExternalIp: Method not implemented");
}


