/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#pragma once


#include "../base/RuleSnatBase.h"

#include "RuleSnatEntry.h"

class Rule;

using namespace polycube::service::model;

class RuleSnat : public RuleSnatBase {
 public:
  RuleSnat(Rule &parent, const RuleSnatJsonObject &conf);
  virtual ~RuleSnat();

  /// <summary>
  /// List of Source NAT rules
  /// </summary>
  std::shared_ptr<RuleSnatEntry> getEntry(const uint32_t &id) override;
  std::vector<std::shared_ptr<RuleSnatEntry>> getEntryList() override;
  void addEntry(const uint32_t &id, const RuleSnatEntryJsonObject &conf) override;
  void addEntryList(const std::vector<RuleSnatEntryJsonObject> &conf) override;
  void replaceEntry(const uint32_t &id, const RuleSnatEntryJsonObject &conf) override;
  void delEntry(const uint32_t &id) override;
  void delEntryList() override;

  RuleSnatAppendOutputJsonObject append(RuleSnatAppendInputJsonObject input) override;
};
