/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#pragma once


#include "../base/RuleMasqueradeBase.h"


class Rule;

using namespace polycube::service::model;

class RuleMasquerade : public RuleMasqueradeBase {
 public:
  RuleMasquerade(Rule &parent, const RuleMasqueradeJsonObject &conf);
  RuleMasquerade(Rule &parent);
  virtual ~RuleMasquerade();

  /// <summary>
  ///
  /// </summary>
  bool getEnabled() override;
  void setEnabled(const bool &value) override;

  RuleMasqueradeEnableOutputJsonObject enable() override;
  RuleMasqueradeDisableOutputJsonObject disable() override;
  void update(const RuleMasqueradeJsonObject &conf);
  RuleMasqueradeJsonObject toJsonObject();
 private:
  bool inject(uint32_t ip); // injects the rule in datapath
  Rule &parent_;
  bool enabled;
};
