/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#pragma once


#include "../base/RuleSnatEntryBase.h"


class RuleSnat;

using namespace polycube::service::model;

class RuleSnatEntry : public RuleSnatEntryBase {
 public:
  RuleSnatEntry(RuleSnat &parent, const RuleSnatEntryJsonObject &conf);
  virtual ~RuleSnatEntry();

  /// <summary>
  /// Rule identifier
  /// </summary>
  uint32_t getId() override;

  /// <summary>
  /// Internal IP address (or subnet)
  /// </summary>
  std::string getInternalNet() override;
  void setInternalNet(const std::string &value) override;

  /// <summary>
  /// Natted source IP address
  /// </summary>
  std::string getExternalIp() override;
  void setExternalIp(const std::string &value) override;
};
