/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "RuleDnatEntry.h"
#include "K8snat.h"


RuleDnatEntry::RuleDnatEntry(RuleDnat &parent, const RuleDnatEntryJsonObject &conf)
    : RuleDnatEntryBase(parent) {
    setExternalIp(conf.getExternalIp());
    setInternalIp(conf.getInternalIp());
}

RuleDnatEntry::~RuleDnatEntry() {}

uint32_t RuleDnatEntry::getId() {
  throw std::runtime_error("RuleDnatEntry::getId: Method not implemented");
}

std::string RuleDnatEntry::getExternalIp() {
  throw std::runtime_error("RuleDnatEntry::getExternalIp: Method not implemented");
}

void RuleDnatEntry::setExternalIp(const std::string &value) {
  throw std::runtime_error("RuleDnatEntry::setExternalIp: Method not implemented");
}

std::string RuleDnatEntry::getInternalIp() {
  throw std::runtime_error("RuleDnatEntry::getInternalIp: Method not implemented");
}

void RuleDnatEntry::setInternalIp(const std::string &value) {
  throw std::runtime_error("RuleDnatEntry::setInternalIp: Method not implemented");
}


