/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "RulePortForwardingEntry.h"
#include "K8snat.h"


RulePortForwardingEntry::RulePortForwardingEntry(RulePortForwarding &parent, const RulePortForwardingEntryJsonObject &conf)
    : RulePortForwardingEntryBase(parent) {
    setExternalIp(conf.getExternalIp());
    setExternalPort(conf.getExternalPort());
  if (conf.protoIsSet()) {
    setProto(conf.getProto());
  }

    setInternalIp(conf.getInternalIp());
    setInternalPort(conf.getInternalPort());
}

RulePortForwardingEntry::~RulePortForwardingEntry() {}

uint32_t RulePortForwardingEntry::getId() {
  throw std::runtime_error("RulePortForwardingEntry::getId: Method not implemented");
}

std::string RulePortForwardingEntry::getExternalIp() {
  throw std::runtime_error("RulePortForwardingEntry::getExternalIp: Method not implemented");
}

void RulePortForwardingEntry::setExternalIp(const std::string &value) {
  throw std::runtime_error("RulePortForwardingEntry::setExternalIp: Method not implemented");
}

uint16_t RulePortForwardingEntry::getExternalPort() {
  throw std::runtime_error("RulePortForwardingEntry::getExternalPort: Method not implemented");
}

void RulePortForwardingEntry::setExternalPort(const uint16_t &value) {
  throw std::runtime_error("RulePortForwardingEntry::setExternalPort: Method not implemented");
}

std::string RulePortForwardingEntry::getProto() {
  throw std::runtime_error("RulePortForwardingEntry::getProto: Method not implemented");
}

void RulePortForwardingEntry::setProto(const std::string &value) {
  throw std::runtime_error("RulePortForwardingEntry::setProto: Method not implemented");
}

std::string RulePortForwardingEntry::getInternalIp() {
  throw std::runtime_error("RulePortForwardingEntry::getInternalIp: Method not implemented");
}

void RulePortForwardingEntry::setInternalIp(const std::string &value) {
  throw std::runtime_error("RulePortForwardingEntry::setInternalIp: Method not implemented");
}

uint16_t RulePortForwardingEntry::getInternalPort() {
  throw std::runtime_error("RulePortForwardingEntry::getInternalPort: Method not implemented");
}

void RulePortForwardingEntry::setInternalPort(const uint16_t &value) {
  throw std::runtime_error("RulePortForwardingEntry::setInternalPort: Method not implemented");
}


