/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#pragma once


#include "../base/RuleDnatEntryBase.h"


class RuleDnat;

using namespace polycube::service::model;

class RuleDnatEntry : public RuleDnatEntryBase {
 public:
  RuleDnatEntry(RuleDnat &parent, const RuleDnatEntryJsonObject &conf);
  virtual ~RuleDnatEntry();

  /// <summary>
  /// Rule identifier
  /// </summary>
  uint32_t getId() override;

  /// <summary>
  /// External destination IP address
  /// </summary>
  std::string getExternalIp() override;
  void setExternalIp(const std::string &value) override;

  /// <summary>
  /// Internal destination IP address
  /// </summary>
  std::string getInternalIp() override;
  void setInternalIp(const std::string &value) override;
};
