/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#pragma once


#include "../base/RulePortForwardingBase.h"

#include "RulePortForwardingEntry.h"

class Rule;

using namespace polycube::service::model;

class RulePortForwarding : public RulePortForwardingBase {
 public:
  RulePortForwarding(Rule &parent, const RulePortForwardingJsonObject &conf);
  virtual ~RulePortForwarding();

  /// <summary>
  /// List of port forwarding rules
  /// </summary>
  std::shared_ptr<RulePortForwardingEntry> getEntry(const uint32_t &id) override;
  std::vector<std::shared_ptr<RulePortForwardingEntry>> getEntryList() override;
  void addEntry(const uint32_t &id, const RulePortForwardingEntryJsonObject &conf) override;
  void addEntryList(const std::vector<RulePortForwardingEntryJsonObject> &conf) override;
  void replaceEntry(const uint32_t &id, const RulePortForwardingEntryJsonObject &conf) override;
  void delEntry(const uint32_t &id) override;
  void delEntryList() override;

  RulePortForwardingAppendOutputJsonObject append(RulePortForwardingAppendInputJsonObject input) override;
};
