/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "NattingTableBase.h"
#include "../K8snat.h"


NattingTableBase::NattingTableBase(K8snat &parent)
    : parent_(parent) {}

NattingTableBase::~NattingTableBase() {}

void NattingTableBase::update(const NattingTableJsonObject &conf) {

  if (conf.originatingRuleIsSet()) {
    setOriginatingRule(conf.getOriginatingRule());
  }
  if (conf.externalIpIsSet()) {
    setExternalIp(conf.getExternalIp());
  }
  if (conf.externalPortIsSet()) {
    setExternalPort(conf.getExternalPort());
  }
}

NattingTableJsonObject NattingTableBase::toJsonObject() {
  NattingTableJsonObject conf;

  conf.setInternalSrc(getInternalSrc());
  conf.setInternalDst(getInternalDst());
  conf.setInternalSport(getInternalSport());
  conf.setInternalDport(getInternalDport());
  conf.setProto(getProto());
  conf.setOriginatingRule(getOriginatingRule());
  conf.setExternalIp(getExternalIp());
  conf.setExternalPort(getExternalPort());

  return conf;
}

std::shared_ptr<spdlog::logger> NattingTableBase::logger() {
  return parent_.logger();
}

