/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* PortsBase.h
*
*
*/

#pragma once

#include "../serializer/PortsJsonObject.h"




#include "polycube/services/cube.h"
#include "polycube/services/port.h"

#include "polycube/services/utils.h"
#include "polycube/services/fifo_map.hpp"

#include <spdlog/spdlog.h>

using namespace polycube::service::model;

class K8snat;
class Ports;

class PortsBase: public polycube::service::Port {
 public:
  PortsBase(polycube::service::Cube<Ports> &parent,
      std::shared_ptr<polycube::service::PortIface> port);
  
  virtual ~PortsBase();
  virtual void update(const PortsJsonObject &conf);
  virtual PortsJsonObject toJsonObject();

  /// <summary>
  /// Type of the k8sNAT port (e.g. FRONTEND or BACKEND)
  /// </summary>
  virtual PortsTypeEnum getType() = 0;
  virtual void setType(const PortsTypeEnum &value) = 0;

  std::shared_ptr<spdlog::logger> logger();
 protected:
  K8snat &parent_;
};
