/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "RulePortForwardingBase.h"
#include "../K8snat.h"


RulePortForwardingBase::RulePortForwardingBase(Rule &parent)
    : parent_(parent) {}

RulePortForwardingBase::~RulePortForwardingBase() {}

void RulePortForwardingBase::update(const RulePortForwardingJsonObject &conf) {

  if (conf.entryIsSet()) {
    for (auto &i : conf.getEntry()) {
      auto id = i.getId();
      auto m = getEntry(id);
      m->update(i);
    }
  }
}

RulePortForwardingJsonObject RulePortForwardingBase::toJsonObject() {
  RulePortForwardingJsonObject conf;

  for(auto &i : getEntryList()) {
    conf.addRulePortForwardingEntry(i->toJsonObject());
  }

  return conf;
}
void RulePortForwardingBase::addEntryList(const std::vector<RulePortForwardingEntryJsonObject> &conf) {
  for (auto &i : conf) {
    uint32_t id_ = i.getId();
    addEntry(id_, i);
  }
}

void RulePortForwardingBase::replaceEntry(const uint32_t &id, const RulePortForwardingEntryJsonObject &conf) {
  delEntry(id);
  uint32_t id_ = conf.getId();
  addEntry(id_, conf);
}

void RulePortForwardingBase::delEntryList() {
  auto elements = getEntryList();
  for (auto &i : elements) {
    uint32_t id_ = i->getId();
    delEntry(id_);
  }
}

std::shared_ptr<spdlog::logger> RulePortForwardingBase::logger() {
  return parent_.logger();
}

