/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "RuleSnatEntryBase.h"
#include "../K8snat.h"


RuleSnatEntryBase::RuleSnatEntryBase(RuleSnat &parent)
    : parent_(parent) {}

RuleSnatEntryBase::~RuleSnatEntryBase() {}

void RuleSnatEntryBase::update(const RuleSnatEntryJsonObject &conf) {

  if (conf.internalNetIsSet()) {
    setInternalNet(conf.getInternalNet());
  }
  if (conf.externalIpIsSet()) {
    setExternalIp(conf.getExternalIp());
  }
}

RuleSnatEntryJsonObject RuleSnatEntryBase::toJsonObject() {
  RuleSnatEntryJsonObject conf;

  conf.setId(getId());
  conf.setInternalNet(getInternalNet());
  conf.setExternalIp(getExternalIp());

  return conf;
}

std::shared_ptr<spdlog::logger> RuleSnatEntryBase::logger() {
  return parent_.logger();
}

