/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* RuleMasqueradeBase.h
*
*
*/

#pragma once

#include "../serializer/RuleMasqueradeJsonObject.h"
#include "../serializer/RuleMasqueradeEnableOutputJsonObject.h"

#include "../serializer/RuleMasqueradeDisableOutputJsonObject.h"







#include <spdlog/spdlog.h>

using namespace polycube::service::model;

class Rule;

class RuleMasqueradeBase {
 public:
  
  RuleMasqueradeBase(Rule &parent);
  
  virtual ~RuleMasqueradeBase();
  virtual void update(const RuleMasqueradeJsonObject &conf);
  virtual RuleMasqueradeJsonObject toJsonObject();

  /// <summary>
  ///
  /// </summary>
  virtual bool getEnabled() = 0;
  virtual void setEnabled(const bool &value) = 0;
  virtual RuleMasqueradeEnableOutputJsonObject enable() = 0;
  virtual RuleMasqueradeDisableOutputJsonObject disable() = 0;

  std::shared_ptr<spdlog::logger> logger();
 protected:
  Rule &parent_;
};
