/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "RuleMasqueradeBase.h"
#include "../K8snat.h"


RuleMasqueradeBase::RuleMasqueradeBase(Rule &parent)
    : parent_(parent) {}

RuleMasqueradeBase::~RuleMasqueradeBase() {}

void RuleMasqueradeBase::update(const RuleMasqueradeJsonObject &conf) {

  if (conf.enabledIsSet()) {
    setEnabled(conf.getEnabled());
  }
}

RuleMasqueradeJsonObject RuleMasqueradeBase::toJsonObject() {
  RuleMasqueradeJsonObject conf;

  conf.setEnabled(getEnabled());

  return conf;
}

std::shared_ptr<spdlog::logger> RuleMasqueradeBase::logger() {
  return parent_.logger();
}

