/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */


#include "RuleDnatBase.h"
#include "../K8snat.h"


RuleDnatBase::RuleDnatBase(Rule &parent)
    : parent_(parent) {}

RuleDnatBase::~RuleDnatBase() {}

void RuleDnatBase::update(const RuleDnatJsonObject &conf) {

  if (conf.entryIsSet()) {
    for (auto &i : conf.getEntry()) {
      auto id = i.getId();
      auto m = getEntry(id);
      m->update(i);
    }
  }
}

RuleDnatJsonObject RuleDnatBase::toJsonObject() {
  RuleDnatJsonObject conf;

  for(auto &i : getEntryList()) {
    conf.addRuleDnatEntry(i->toJsonObject());
  }

  return conf;
}
void RuleDnatBase::addEntryList(const std::vector<RuleDnatEntryJsonObject> &conf) {
  for (auto &i : conf) {
    uint32_t id_ = i.getId();
    addEntry(id_, i);
  }
}

void RuleDnatBase::replaceEntry(const uint32_t &id, const RuleDnatEntryJsonObject &conf) {
  delEntry(id);
  uint32_t id_ = conf.getId();
  addEntry(id_, conf);
}

void RuleDnatBase::delEntryList() {
  auto elements = getEntryList();
  for (auto &i : elements) {
    uint32_t id_ = i->getId();
    delEntry(id_);
  }
}

std::shared_ptr<spdlog::logger> RuleDnatBase::logger() {
  return parent_.logger();
}

