/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "K8snatJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

K8snatJsonObject::K8snatJsonObject() {
  m_nameIsSet = false;
  m_portsIsSet = false;
  m_ruleIsSet = false;
  m_nattingTableIsSet = false;
}

K8snatJsonObject::K8snatJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_nameIsSet = false;
  m_portsIsSet = false;
  m_ruleIsSet = false;
  m_nattingTableIsSet = false;


  if (val.count("name")) {
    setName(val.at("name").get<std::string>());
  }

  if (val.count("ports")) {
    for (auto& item : val["ports"]) {
      PortsJsonObject newItem{ item };
      m_ports.push_back(newItem);
    }

    m_portsIsSet = true;
  }

  if (val.count("rule")) {
    if (!val["rule"].is_null()) {
      RuleJsonObject newItem { val["rule"] };
      setRule(newItem);
    }
  }

  if (val.count("natting-table")) {
    for (auto& item : val["natting-table"]) {
      NattingTableJsonObject newItem{ item };
      m_nattingTable.push_back(newItem);
    }

    m_nattingTableIsSet = true;
  }
}

nlohmann::json K8snatJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_nameIsSet) {
    val["name"] = m_name;
  }

  {
    nlohmann::json jsonArray;
    for (auto& item : m_ports) {
      jsonArray.push_back(JsonObjectBase::toJson(item));
    }

    if (jsonArray.size() > 0) {
      val["ports"] = jsonArray;
    }
  }

  if (m_ruleIsSet) {
    val["rule"] = JsonObjectBase::toJson(m_rule);
  }

  {
    nlohmann::json jsonArray;
    for (auto& item : m_nattingTable) {
      jsonArray.push_back(JsonObjectBase::toJson(item));
    }

    if (jsonArray.size() > 0) {
      val["natting-table"] = jsonArray;
    }
  }

  return val;
}

std::string K8snatJsonObject::getName() const {
  return m_name;
}

void K8snatJsonObject::setName(std::string value) {
  m_name = value;
  m_nameIsSet = true;
}

bool K8snatJsonObject::nameIsSet() const {
  return m_nameIsSet;
}



const std::vector<PortsJsonObject>& K8snatJsonObject::getPorts() const{
  return m_ports;
}

void K8snatJsonObject::addPorts(PortsJsonObject value) {
  m_ports.push_back(value);
  m_portsIsSet = true;
}


bool K8snatJsonObject::portsIsSet() const {
  return m_portsIsSet;
}

void K8snatJsonObject::unsetPorts() {
  m_portsIsSet = false;
}

RuleJsonObject K8snatJsonObject::getRule() const {
  return m_rule;
}

void K8snatJsonObject::setRule(RuleJsonObject value) {
  m_rule = value;
  m_ruleIsSet = true;
}

bool K8snatJsonObject::ruleIsSet() const {
  return m_ruleIsSet;
}

void K8snatJsonObject::unsetRule() {
  m_ruleIsSet = false;
}

const std::vector<NattingTableJsonObject>& K8snatJsonObject::getNattingTable() const{
  return m_nattingTable;
}

void K8snatJsonObject::addNattingTable(NattingTableJsonObject value) {
  m_nattingTable.push_back(value);
  m_nattingTableIsSet = true;
}


bool K8snatJsonObject::nattingTableIsSet() const {
  return m_nattingTableIsSet;
}

void K8snatJsonObject::unsetNattingTable() {
  m_nattingTableIsSet = false;
}


}
}
}

