/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* K8snatJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"

#include "PortsJsonObject.h"
#include "RuleJsonObject.h"
#include <vector>
#include "NattingTableJsonObject.h"
#include "polycube/services/cube.h"

namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  K8snatJsonObject : public JsonObjectBase {
public:
  K8snatJsonObject();
  K8snatJsonObject(const nlohmann::json &json);
  ~K8snatJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// Name of the k8snat service
  /// </summary>
  std::string getName() const;
  void setName(std::string value);
  bool nameIsSet() const;

  /// <summary>
  /// Entry of the ports table
  /// </summary>
  const std::vector<PortsJsonObject>& getPorts() const;
  void addPorts(PortsJsonObject value);
  bool portsIsSet() const;
  void unsetPorts();

  /// <summary>
  ///
  /// </summary>
  RuleJsonObject getRule() const;
  void setRule(RuleJsonObject value);
  bool ruleIsSet() const;
  void unsetRule();

  /// <summary>
  ///
  /// </summary>
  const std::vector<NattingTableJsonObject>& getNattingTable() const;
  void addNattingTable(NattingTableJsonObject value);
  bool nattingTableIsSet() const;
  void unsetNattingTable();

private:
  std::string m_name;
  bool m_nameIsSet;
  std::vector<PortsJsonObject> m_ports;
  bool m_portsIsSet;
  RuleJsonObject m_rule;
  bool m_ruleIsSet;
  std::vector<NattingTableJsonObject> m_nattingTable;
  bool m_nattingTableIsSet;
};

}
}
}

