/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* RulePortForwardingAppendOutputJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"


namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  RulePortForwardingAppendOutputJsonObject : public JsonObjectBase {
public:
  RulePortForwardingAppendOutputJsonObject();
  RulePortForwardingAppendOutputJsonObject(const nlohmann::json &json);
  ~RulePortForwardingAppendOutputJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  ///
  /// </summary>
  uint32_t getId() const;
  void setId(uint32_t value);
  bool idIsSet() const;
  void unsetId();

private:
  uint32_t m_id;
  bool m_idIsSet;
};

}
}
}

