/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */



#include "RuleSnatAppendInputJsonObject.h"
#include <regex>

namespace polycube {
namespace service {
namespace model {

RuleSnatAppendInputJsonObject::RuleSnatAppendInputJsonObject() {
  m_internalNetIsSet = false;
  m_externalIpIsSet = false;
}

RuleSnatAppendInputJsonObject::RuleSnatAppendInputJsonObject(const nlohmann::json &val) :
  JsonObjectBase(val) {
  m_internalNetIsSet = false;
  m_externalIpIsSet = false;


  if (val.count("internal-net")) {
    setInternalNet(val.at("internal-net").get<std::string>());
  }

  if (val.count("external-ip")) {
    setExternalIp(val.at("external-ip").get<std::string>());
  }
}

nlohmann::json RuleSnatAppendInputJsonObject::toJson() const {
  nlohmann::json val = nlohmann::json::object();
  if (!getBase().is_null()) {
    val.update(getBase());
  }

  if (m_internalNetIsSet) {
    val["internal-net"] = m_internalNet;
  }

  if (m_externalIpIsSet) {
    val["external-ip"] = m_externalIp;
  }

  return val;
}

std::string RuleSnatAppendInputJsonObject::getInternalNet() const {
  return m_internalNet;
}

void RuleSnatAppendInputJsonObject::setInternalNet(std::string value) {
  m_internalNet = value;
  m_internalNetIsSet = true;
}

bool RuleSnatAppendInputJsonObject::internalNetIsSet() const {
  return m_internalNetIsSet;
}



std::string RuleSnatAppendInputJsonObject::getExternalIp() const {
  return m_externalIp;
}

void RuleSnatAppendInputJsonObject::setExternalIp(std::string value) {
  m_externalIp = value;
  m_externalIpIsSet = true;
}

bool RuleSnatAppendInputJsonObject::externalIpIsSet() const {
  return m_externalIpIsSet;
}




}
}
}

