/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* RuleDnatAppendInputJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"


namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  RuleDnatAppendInputJsonObject : public JsonObjectBase {
public:
  RuleDnatAppendInputJsonObject();
  RuleDnatAppendInputJsonObject(const nlohmann::json &json);
  ~RuleDnatAppendInputJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// External destination IP address
  /// </summary>
  std::string getExternalIp() const;
  void setExternalIp(std::string value);
  bool externalIpIsSet() const;

  /// <summary>
  /// Internal destination IP address
  /// </summary>
  std::string getInternalIp() const;
  void setInternalIp(std::string value);
  bool internalIpIsSet() const;

private:
  std::string m_externalIp;
  bool m_externalIpIsSet;
  std::string m_internalIp;
  bool m_internalIpIsSet;
};

}
}
}

