/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* RuleMasqueradeEnableOutputJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"


namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  RuleMasqueradeEnableOutputJsonObject : public JsonObjectBase {
public:
  RuleMasqueradeEnableOutputJsonObject();
  RuleMasqueradeEnableOutputJsonObject(const nlohmann::json &json);
  ~RuleMasqueradeEnableOutputJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// True if the operation is successful
  /// </summary>
  bool getResult() const;
  void setResult(bool value);
  bool resultIsSet() const;
  void unsetResult();

private:
  bool m_result;
  bool m_resultIsSet;
};

}
}
}

