/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* RulePortForwardingJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"

#include "RulePortForwardingEntryJsonObject.h"
#include <vector>

namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  RulePortForwardingJsonObject : public JsonObjectBase {
public:
  RulePortForwardingJsonObject();
  RulePortForwardingJsonObject(const nlohmann::json &json);
  ~RulePortForwardingJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// List of port forwarding rules
  /// </summary>
  const std::vector<RulePortForwardingEntryJsonObject>& getEntry() const;
  void addRulePortForwardingEntry(RulePortForwardingEntryJsonObject value);
  bool entryIsSet() const;
  void unsetEntry();

private:
  std::vector<RulePortForwardingEntryJsonObject> m_entry;
  bool m_entryIsSet;
};

}
}
}

