/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* RuleSnatJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"

#include <vector>
#include "RuleSnatEntryJsonObject.h"

namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  RuleSnatJsonObject : public JsonObjectBase {
public:
  RuleSnatJsonObject();
  RuleSnatJsonObject(const nlohmann::json &json);
  ~RuleSnatJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// List of Source NAT rules
  /// </summary>
  const std::vector<RuleSnatEntryJsonObject>& getEntry() const;
  void addRuleSnatEntry(RuleSnatEntryJsonObject value);
  bool entryIsSet() const;
  void unsetEntry();

private:
  std::vector<RuleSnatEntryJsonObject> m_entry;
  bool m_entryIsSet;
};

}
}
}

