/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* RuleDnatJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"

#include "RuleDnatEntryJsonObject.h"
#include <vector>

namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  RuleDnatJsonObject : public JsonObjectBase {
public:
  RuleDnatJsonObject();
  RuleDnatJsonObject(const nlohmann::json &json);
  ~RuleDnatJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// List of Destination NAT rules
  /// </summary>
  const std::vector<RuleDnatEntryJsonObject>& getEntry() const;
  void addRuleDnatEntry(RuleDnatEntryJsonObject value);
  bool entryIsSet() const;
  void unsetEntry();

private:
  std::vector<RuleDnatEntryJsonObject> m_entry;
  bool m_entryIsSet;
};

}
}
}

