/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* RuleJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"

#include "RuleMasqueradeJsonObject.h"
#include "RulePortForwardingJsonObject.h"
#include "RuleDnatJsonObject.h"
#include "RuleSnatJsonObject.h"

namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  RuleJsonObject : public JsonObjectBase {
public:
  RuleJsonObject();
  RuleJsonObject(const nlohmann::json &json);
  ~RuleJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  ///
  /// </summary>
  RuleSnatJsonObject getSnat() const;
  void setSnat(RuleSnatJsonObject value);
  bool snatIsSet() const;
  void unsetSnat();

  /// <summary>
  ///
  /// </summary>
  RuleMasqueradeJsonObject getMasquerade() const;
  void setMasquerade(RuleMasqueradeJsonObject value);
  bool masqueradeIsSet() const;
  void unsetMasquerade();

  /// <summary>
  ///
  /// </summary>
  RuleDnatJsonObject getDnat() const;
  void setDnat(RuleDnatJsonObject value);
  bool dnatIsSet() const;
  void unsetDnat();

  /// <summary>
  ///
  /// </summary>
  RulePortForwardingJsonObject getPortForwarding() const;
  void setPortForwarding(RulePortForwardingJsonObject value);
  bool portForwardingIsSet() const;
  void unsetPortForwarding();

private:
  RuleSnatJsonObject m_snat;
  bool m_snatIsSet;
  RuleMasqueradeJsonObject m_masquerade;
  bool m_masqueradeIsSet;
  RuleDnatJsonObject m_dnat;
  bool m_dnatIsSet;
  RulePortForwardingJsonObject m_portForwarding;
  bool m_portForwardingIsSet;
};

}
}
}

