/**
* k8snat API generated from k8snat.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* RuleSnatEntryJsonObject.h
*
*
*/

#pragma once


#include "JsonObjectBase.h"


namespace polycube {
namespace service {
namespace model {


/// <summary>
///
/// </summary>
class  RuleSnatEntryJsonObject : public JsonObjectBase {
public:
  RuleSnatEntryJsonObject();
  RuleSnatEntryJsonObject(const nlohmann::json &json);
  ~RuleSnatEntryJsonObject() final = default;
  nlohmann::json toJson() const final;


  /// <summary>
  /// Rule identifier
  /// </summary>
  uint32_t getId() const;
  void setId(uint32_t value);
  bool idIsSet() const;

  /// <summary>
  /// Internal IP address (or subnet)
  /// </summary>
  std::string getInternalNet() const;
  void setInternalNet(std::string value);
  bool internalNetIsSet() const;

  /// <summary>
  /// Natted source IP address
  /// </summary>
  std::string getExternalIp() const;
  void setExternalIp(std::string value);
  bool externalIpIsSet() const;

private:
  uint32_t m_id;
  bool m_idIsSet;
  std::string m_internalNet;
  bool m_internalNetIsSet;
  std::string m_externalIp;
  bool m_externalIpIsSet;
};

}
}
}

