/**
* k8slbrp API generated from k8slbrp.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#pragma once


#include "../base/PortsBase.h"


class K8slbrp;

using namespace polycube::service::model;

class Ports : public PortsBase {
 public:
  Ports(polycube::service::Cube<Ports> &parent,
      std::shared_ptr<polycube::service::PortIface> port,
      const PortsJsonObject &conf);
  virtual ~Ports();

  /// <summary>
  /// Type of the LB port (e.g. FRONTEND or BACKEND)
  /// </summary>
  PortsTypeEnum getType() override;
  void setType(const PortsTypeEnum &value) override;
};
