/**
* k8slbrp API generated from k8slbrp.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


#pragma once


#include "../base/SrcIpRewriteBase.h"


class K8slbrp;

using namespace polycube::service::model;

class SrcIpRewrite : public SrcIpRewriteBase {
 public:
  SrcIpRewrite(K8slbrp &parent, const SrcIpRewriteJsonObject &conf);
  virtual ~SrcIpRewrite();

  /// <summary>
  /// Range of IP addresses of the clients that must be replaced
  /// </summary>
  std::string getIpRange() override;
  void setIpRange(const std::string &value) override;

  /// <summary>
  /// Range of IP addresses of the that must be used to replace client addresses
  /// </summary>
  std::string getNewIpRange() override;
  void setNewIpRange(const std::string &value) override;
};
