/**
* k8slbrp API generated from k8slbrp.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "SrcIpRewrite.h"
#include "K8slbrp.h"


SrcIpRewrite::SrcIpRewrite(K8slbrp &parent, const SrcIpRewriteJsonObject &conf)
    : SrcIpRewriteBase(parent) {
  if (conf.ipRangeIsSet()) {
    setIpRange(conf.getIpRange());
  }

  if (conf.newIpRangeIsSet()) {
    setNewIpRange(conf.getNewIpRange());
  }

}

SrcIpRewrite::~SrcIpRewrite() {}

std::string SrcIpRewrite::getIpRange() {
  throw std::runtime_error("SrcIpRewrite::getIpRange: Method not implemented");
}

void SrcIpRewrite::setIpRange(const std::string &value) {
  throw std::runtime_error("SrcIpRewrite::setIpRange: Method not implemented");
}

std::string SrcIpRewrite::getNewIpRange() {
  throw std::runtime_error("SrcIpRewrite::getNewIpRange: Method not implemented");
}

void SrcIpRewrite::setNewIpRange(const std::string &value) {
  throw std::runtime_error("SrcIpRewrite::setNewIpRange: Method not implemented");
}


