/**
* k8sdispatcher API generated from k8sdispatcher.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


// TODO: Modify these methods with your own implementation


#include "NodeportRule.h"
#include "K8sdispatcher.h"


NodeportRule::NodeportRule(K8sdispatcher &parent, const NodeportRuleJsonObject &conf)
    : NodeportRuleBase(parent) {
  if (conf.internalSrcIsSet()) {
    setInternalSrc(conf.getInternalSrc());
  }

}

NodeportRule::~NodeportRule() {}

std::string NodeportRule::getInternalSrc() {
  throw std::runtime_error("NodeportRule::getInternalSrc: Method not implemented");
}

void NodeportRule::setInternalSrc(const std::string &value) {
  throw std::runtime_error("NodeportRule::setInternalSrc: Method not implemented");
}

uint16_t NodeportRule::getNodeportPort() {
  throw std::runtime_error("NodeportRule::getNodeportPort: Method not implemented");
}

std::string NodeportRule::getProto() {
  throw std::runtime_error("NodeportRule::getProto: Method not implemented");
}


