/**
* k8sdispatcher API generated from k8sdispatcher.yang
*
* NOTE: This file is auto generated by polycube-codegen
* https://github.com/polycube-network/polycube-codegen
*/


/* Do not edit this file manually */

/*
* K8sdispatcherBase.h
*
*
*/

#pragma once

#include "../serializer/K8sdispatcherJsonObject.h"

#include "../NattingTable.h"
#include "../Ports.h"

#include "polycube/services/cube.h"
#include "polycube/services/port.h"



#include "polycube/services/utils.h"
#include "polycube/services/fifo_map.hpp"

#include <spdlog/spdlog.h>

using namespace polycube::service::model;


class K8sdispatcherBase: public virtual polycube::service::Cube<Ports> {
 public:
  K8sdispatcherBase(const std::string name);
  
  virtual ~K8sdispatcherBase();
  virtual void update(const K8sdispatcherJsonObject &conf);
  virtual K8sdispatcherJsonObject toJsonObject();

  /// <summary>
  /// Entry of the ports table
  /// </summary>
  virtual std::shared_ptr<Ports> getPorts(const std::string &name);
  virtual std::vector<std::shared_ptr<Ports>> getPortsList();
  virtual void addPorts(const std::string &name, const PortsJsonObject &conf);
  virtual void addPortsList(const std::vector<PortsJsonObject> &conf);
  virtual void replacePorts(const std::string &name, const PortsJsonObject &conf);
  virtual void delPorts(const std::string &name);
  virtual void delPortsList();

  /// <summary>
  /// Range of VIPs where clusterIP services are exposed
  /// </summary>
  virtual std::string getClusterIpSubnet() = 0;
  virtual void setClusterIpSubnet(const std::string &value) = 0;

  /// <summary>
  /// Range of IPs of pods in this node
  /// </summary>
  virtual std::string getClientSubnet() = 0;
  virtual void setClientSubnet(const std::string &value) = 0;

  /// <summary>
  /// Range where client&#39;s IPs are mapped into
  /// </summary>
  virtual std::string getVirtualClientSubnet() = 0;
  virtual void setVirtualClientSubnet(const std::string &value) = 0;

  /// <summary>
  ///
  /// </summary>
  virtual std::shared_ptr<NattingTable> getNattingTable(const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto) = 0;
  virtual std::vector<std::shared_ptr<NattingTable>> getNattingTableList() = 0;
  virtual void addNattingTable(const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const NattingTableJsonObject &conf) = 0;
  virtual void addNattingTableList(const std::vector<NattingTableJsonObject> &conf);
  virtual void replaceNattingTable(const std::string &internalSrc, const std::string &internalDst, const uint16_t &internalSport, const uint16_t &internalDport, const std::string &proto, const NattingTableJsonObject &conf);
  virtual void delNattingTable(const std::string &internalSrc,const std::string &internalDst,const uint16_t &internalSport,const uint16_t &internalDport,const std::string &proto) = 0;
  virtual void delNattingTableList();

  /// <summary>
  /// Port range used for NodePort services
  /// </summary>
  virtual std::string getNodeportRange() = 0;
  virtual void setNodeportRange(const std::string &value) = 0;
};
